apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard
spec:
  tls:
    - hosts: [dash.west4.kz-eu.k8s.2600hz.dev]
      secretName: dashboard-tls
  rules:
    - host: dash.west4.kz-eu.k8s.2600hz.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: {service: {name: kubernetes-dashboard-http, port: {number: 9090}}}
